import i18next from "i18next"

const {t} =i18next;
export const compositionOptions=[
    {"value": "Symmetrical face", "label": "对称面孔"},
    {"value": "volumetric light/Volume Method", "label": "体积光"},
    {"value": "Symmetrical composition", "label": "对称构图"},
    {"value": "Asymmetrical composition", "label": "非对称构图"},
    {"value": "Rule of Thirds composition", "label": "三分法构图"},
    {"value": "Golden Ratio composition", "label": "黄金分割构图"},
    {"value": "Diagonal composition", "label": "对角线构图"},
    {"value": "Dynamic symmetry composition", "label": "动态对称构图"},
    {"value": "Juxtaposition composition", "label": "并列构图"},
    {"value": "Converging lines composition", "label": "汇聚线条构图"},
    {"value": "Vanishing point composition", "label": "消失点构图"},
    {"value": "Framing composition", "label": "画框构图"},
    {"value": "Nonlinear composition", "label": "非线性构图"},
    {"value": "Saturated composition", "label": "饱和构图"},
    {"value": "Point of view composition", "label": "视角构图"},
    {"value": "Cut out composition", "label": "剪影构图"},
    {"value": "Repetition composition", "label": "重复构图"},
    {"value": "Focal point composition", "label": "焦点构图"},
    {"value": "Contrast composition", "label": "对比构图"},
    {"value": "Overlapping composition", "label": "重叠构图"},
    {"value": "Center the composition", "label": "中心构图"},
    {"value": "S-shaped composition", "label": "S形构图"},
    {"value": "Horizontal composition", "label": "横向构图"},
    {"value": "Mandelbrot", "label": "曼德博集合"},
    {"value": "Wide view", "label": "宽景"},
    {"value": "Bird view", "label": "鸟瞰"},
    {"value": "Top view", "label": "俯视"},
    {"value": "Up view", "label": "仰视"},
    {"value": "Front view", "label": "正面"},
    {"value": "Headshot", "label": "头部特写"},
    {"value": "Utrawide shot", "label": "超广角"},
    {"value": "Extreme closeup", "label": "极端特写"},
    {"value": "Macro shot", "label": "微距"},
    {"value": "An expansive view of", "label": "景观"},
    {"value": "Portrait", "label": "肖像"},
    {"value": "Fullbody", "label": "全身"},
    {"value": "Busts", "label": "半身像"},
    {"value": "Close up", "label": "特写"},
    {"value": "Profile", "label": "侧面"},
    {"value": "Symmetrical body", "label": "对称身体"},
    {"value": "Isolation composition", "label": "孤立构图"},
    {"value": "Radial composition", "label": "径向构图"},
    {"value": "split complementary composition", "label": "分割互补构图"},
    {"value": "Mise-en-scene composition", "label": "布景构图"},
    {"value": "Negative space composition", "label": "负空问构图"},
    {"value": "Collage composition", "label": "拼贴构图"},
    {"value": "Rule of Thirds", "label": "三分法"},
    {"value": "Golden Ratio", "label": "黄金分割"},
    {"value": "Symmetry", "label": "对称"},
    {"value": "Asymmetry", "label": "不对称"},
    {"value": "Leading Lines", "label": "引导线"},
    {"value": "Framing", "label": "构框"},
    {"value": "Isolation", "label": "孤立"},
    {"value": "Depth", "label": "深度"},
    {"value": "Contrast", "label": "对比"},
    {"value": "Texture", "label": "纹理"},
    {"value": "Free camera", "label": "自由视角"},
    {"value": "Fixed camera", "label": "固定视角"},
    {"value": "Top-down perspective", "label": "俯视视角"},
    {"value": "Side-scrolling perspective", "label": "侧面视角"},
    {"value": "Close-up view", "label": "短距离视角"},
    {"value": "Long-shot view", "label": "远距离视角"},
    {"value": "Arbitrary view", "label": "随意视角"},
    {"value": "Panoramic view", "label": "全景视角"},
    {"value": "Backlight style", "label": "逆光摄影风格"},
    {"value": "Low Angle Shot", "label": "低角度视角"},
    {"value": "Overhead", "label": "俯拍视角"},
    {"value": "Eye-level", "label": "常规视角"},
    {"value": "Bird's-eye", "label": "鸟瞰视角"},
    {"value": "Dutch", "label": "交错视角"},
    {"value": "Dynamic", "label": "运动视角"},
    {"value": "Extreme Close-up", "label": "极限特写"},
    {"value": "Perspective", "label": "透视视角"},
    {"value": "Detroit: Become Human camera angle", "label": "底特律视角"},
    {"value": "Simulated camera", "label": "模拟摄影机"},
    {"value": "Follow camera", "label": "跟随视角"},
    {"value": "Endoscopic view", "label": "内视镜视角"},
    {"value": "Over the shoulder", "label": "肩膀视角"},
    {"value": "Fisheye lens", "label": "鱼眼视角"},
    {"value": "Macro lens", "label": "微距视角"},
    {"value": "Reverse angle", "label": "反转视角"},
    {"value": "Close-Up(CU)", "label": "特写"},
    {"value": "Medium Close-up(MCu)", "label": "中特写"},
    {"value": "Medium Shot(Ms)", "label": "中景"},
    {"value": "Medium Long Shot(MLS)", "label": "中远暴"},
    {"value": "Long Shot(LS)", "label": "远景"},
    {"value": "Over the Shoulder Shot", "label": "过肩景"},
    {"value": "Loose Shot", "label": "松散景"},
    {"value": "Tight Shot", "label": "近距离景"},
    {"value": "Group Shot(GS)", "label": "群景"},
    {"value": "Scenery Shot", "label": "风景照"},
    {"value": "Bokeh", "label": "背景虚化"},
    {"value": "Foreground", "label": "前景"},
    {"value": "Background", "label": "背景"},
    {"value": "Detail Shot(ECU)", "label": "大特写"},
    {"value": "Chest shot(MCU)", "label": "胸部以上"},
    {"value": "Waist Shot(ws)", "label": "腰部以上"},
    {"value": "Knee Shot(Ks)", "label": "膝盖以上"},
    {"value": "Extra Long Shot(ELS)", "label": "人在远方"},
    {"value": "Big Close-Up(BCu)", "label": "头部以上"},
    {"value": "Face Shot (vCu)", "label": "脸部特写"},
    {"value": "A Bird's-Eye View, Aerial View", "label": "鸟瞰图"},
    {"value": "Top View", "label": "顶视園"},
    {"value": "Tilt-Shift", "label": "倾斜移位"},
    {"value": "Satelite View", "label": "卫星视图"},
    {"value": "Bottom View", "label": "底视图"},
    {"value": "Front, side, Rear view", "label": "前视、侧视、后视图"},
    {"value": "Product View", "label": "产品视图"},
    {"value": "Extreme Closeup View", "label": "极端特写视图"},
    {"value": "Look Up", "label": "仰视"},
    {"value": "First-Person View", "label": "第一人称视角"},
    {"value": "Isometric View", "label": "等距视图"},
    {"value": "Closeup View", "label": "特写视图"},
    {"value": "High Angle View", "label": "高角度视图"}
  ]
  

  export const qualityOptions = [{
    value: ".25",
    label: t("Standard")
  }, {
    value: ".5",
    label: t("Normal")
  }, {
    value: "1",
    label: t("High Definition")
  }, {
    value: "2",
    label: t("Ultra High Definition")
  }]



  export const styleOptions = [{
    value: "",
    label: t("default")
  }, {
    value: "expressive",
    label: t("expressive")
  }, {
    value: "cute",
    label: t("cute")
  }, {
    value: "scenic",
    label: t("scenic")
  }]


  export const style2Options = [
        {"value": "Tradition Chinese Ink Painting", "label": "东方山水画"},
        {"value": "Chinese-style", "label": "中式风格"},
        {"value": "ink illustration", "label": "水墨插图"},
        {"value": "New Chinese Style", "label": "新中式风格"},
        {"value": "Ink Wash Painting Style", "label": "水墨风格"},
        {"value": "color ink on paper", "label": "纸本彩色墨水"},
        {"value": "Traditional culture", "label": "传统文化"},
        {"value": "Japanese Ukiyo-e", "label": "浮世绘"},
        {"value": "Japanese comics/manga", "label": "日本漫画风格"},
        {"value": "poster of japanese graphic design", "label": "日本海报风格"},
        {"value": "Anime", "label": "日本动画片"},
        {"value": "Miyazaki Hayao style", "label": "宫崎骏风格"},
        {"value": "Soejima Shigenori", "label": "副岛成记"},
        {"value": "Yamada Akihiro", "label": "山田章博"},
        {"value": "Ghibli Studio", "label": "吉卜力风格"},
        {"value": "joio's bizarre adventure", "label": "Jolo的奇妙冒险"},
        {"value": "manga", "label": "漫画"},
        {"value": "Japanese-style", "label": "日本风格"},
        {"value": "Magic realism", "label": "魔幻现实"},
        {"value": "Disney-style", "label": "迪士尼风"},
        {"value": "ACGN", "label": "二次元"},
        {"value": "Makoto Shinkai", "label": "新海诚"},
        {"value": "Lolita", "label": "洛丽塔风格"},
        {"value": "stock illustration style", "label": "童话故事书插图风格"},
        {"value": "Watercolor children's illustration", "label": "水彩儿童插画"},
        {"value": "Munashichi", "label": "六七质"},
        {"value": "Hand-drawn style", "label": "手绘风格"},
        {"value": "Cartoon", "label": "卡通"},
        {"value": "Pixel art", "label": "像素风"},
        {"value": "Fairy tale style", "label": "童话风格"},
        {"value": "doodle", "label": "涂鸦"},
        {"value": "Voynich manuscript", "label": "伏尼契手稿"},
        {"value": "CGSociety", "label": "梦工厂动西风格"},
        {"value": "Dreamworks Pictures", "label": "梦工厂黜业"},
        {"value": "Pixar", "label": "皮克斯"},
        {"value": "Pulp Noir", "label": "黑白电影时期"},
        {"value": "Hollywood-style", "label": "电影风格"},
        {"value": "Cinematography style", "label": "电影摄影风格"},
        {"value": "Miniature movie style", "label": "微缩模型电影风格"},
        {"value": "film photography", "label": "剪辑"},
        {"value": "montage", "label": "蒙太奇"},
        {"value": "black and white", "label": "黑白"},
        {"value": "Fashion", "label": "时尚"},
        {"value": "Modern-style", "label": "现代风格"},
        {"value": "interior design", "label": "室内设计"},
        {"value": "Eco-friendly-style", "label": "环保清新风格"},
        {"value": "Country style", "label": "乡村风格"},
        {"value": "Minimalism", "label": "极简主义"},
        {"value": "Immersive design", "label": "沉浸式设计"},
        {"value": "Mystic fantasy", "label": "神秘幻想"},
        {"value": "Modern Minimalist", "label": "现代简约风格"},
        {"value": "Prairie", "label": "草原风格"},
        {"value": "Modern Luxury", "label": "现代奢华风格"},
        {"value": "Forest", "label": "森林风格"},
        {"value": "Ocean", "label": "海洋风格"},
        {"value": "Art Deco style", "label": "艺术装饰风格"},
        {"value": "pearl Milk Tea Style", "label": "珍珠奶茶风格"},
        {"value": "pointillism", "label": "点彩派"},
        {"value": "claude Monet", "label": "克劳德莫奈"},
        {"value": "quilted art", "label": "绗缝艺术"},
        {"value": "partial anatomy", "label": "局部解剖戏"},
        {"value": "9os video game", "label": "90年代电视游戏"},
        {"value": "Game-style", "label": "游戏风格"},
        {"value": "botw", "label": "旷野之息"},
        {"value": "Warframe", "label": "星际战甲"},
        {"value": "Pokemon", "label": "宝可梦"},
        {"value": "x英雄 APEX", "label": "ApeThe Elder Scrolls 上古卷轴"},
        {"value": "From Software", "label": "魂系游戏"},
        {"value": "Detroit: Become Human", "label": "底特律：变人"},
        {"value": "AFK Arena", "label": "剑与远征"},
        {"value": "cookierun kingdom and 跑跑姜饼人", "label": "League of legends 英雄联盟"},
        {"value": "weapon design", "label": "武器设计"},
        {"value": "Game scene graph", "label": "游戏场景图"},
        {"value": "character concept art", "label": "角色概念艺术"},
        {"value": "素风 8、16、24bit", "label": "8、16、24像素画"},
        {"value": "painting", "label": "油画"},
        {"value": "Acrylic painting", "label": "丙烯画"},
        {"value": "volumetric lihht", "label": "体积法"},
        {"value": "french art", "label": "法国艺术"},
        {"value": "Bauhaus", "label": "包豪斯"},
        {"value": "Unity Creations", "label": "统一创作"},
        {"value": "Leonardo Da Vinci", "label": "达芬奇"},
        {"value": "Vincent Van Gogh", "label": "梵高"},
        {"value": "Baroque", "label": "巴洛克吋期"},
        {"value": "Impressionism", "label": "印象派"},
        {"value": "Art Nouveau", "label": "新艺术风格"},
        {"value": "ROCoCO", "label": "洛可可"},
        {"value": "Renaissance", "label": "文艺复兴"},
        {"value": "Cubism", "label": "立体派"},
        {"value": "Stained glass window", "label": "彩色玻璃窗"},
        {"value": "Abstract Art", "label": "抽象表现主义"},
        {"value": "Surrealism", "label": "超现实主义"},
        {"value": "OP Art /Optical Art", "label": "欧普艺术/光效应艺术"},
        {"value": "Abstract", "label": "抽象风"},
        {"value": "Gothic gloomy realism", "label": "写实主义"},
        {"value": "Ethnic Art", "label": "民族艺术"},
        {"value": "riso ", "label": "民族艺术"},
        {"value": "gothic-style", "label": "哥特式"},
        {"value": "full details", "label": "哥特式黑暗"},
        {"value": "Fauvism", "label": "野兽派"},
        {"value": "Minimalist", "label": "极简主义"},
        {"value": "brutalist", "label": "粗犷主义"},
        {"value": "Constructivist", "label": "建构主义"},
        {"value": "concept art", "label": "概念艺术"},
        {"value": "American Country", "label": "美式乡村风格"},
        {"value": "Industrial", "label": "工业风格"},
        {"value": "Carving Art", "label": "雕刻艺术风格"},
        {"value": "Ethnic", "label": "民族风格"},
        {"value": "Magic Realism Style", "label": "魔幻现实主义风格"},
        {"value": "book page", "label": "书页"},
        {"value": "realistic", "label": "真实的"},
        {"value": "3D", "label": "3D风"},
        {"value": "sophisticated", "label": "复杂的"},
        {"value": "photoreal", "label": "真实感"},
        {"value": "national geographic", "label": "国家地理"},
        {"value": "hyperrealism", "label": "超写实主义"},
        {"value": "cinematic", "label": "电影般的"},
        {"value": "architectural sketching", "label": "建筑素描"},
        {"value": "Stained glass window", "label": "彩色玻璃窗"},
        {"value": "Abstract Art", "label": "抽象表现主义"},
        {"value": "Acrylic painting", "label": "丙烯画"},
        {"value": "volumetric lihht", "label": "体积法"},
        {"value": "American Country", "label": "美式乡村风格"},
        {"value": "Pulp Noir", "label": "黑白电影时期"},
        {"value": "Hollywood-style", "label": "电影风格"},
        {"value": "Disney-style", "label": "迪士尼风"}      
  ]

  export const lightOptions=[
    {"value": "Crystal Blue", "label": "水晶蓝色系"},
    {"value": "shine", "label": "发光"},
    {"value": "star flash", "label": "星闪"},
    {"value": "fluorescence", "label": "荧光"},
    {"value": "holy light", "label": "圣光"},
    {"value": "reflections transparent iridescent colors", "label": "反射透明彩虹色"},
    {"value": "Candy", "label": "糖果色系"},
    {"value": "Coral", "label": "珊瑚色系"},
    {"value": "Lavender", "label": "紫罗兰色系"},
    {"value": "Emerald", "label": "绿野仙踪色系"},
    {"value": "Rose Gold", "label": "玫瑰金色系"},
    {"value": "sky Blue", "label": "浅蓝色系"},
    {"value": "Burgundy", "label": "酒红色系"},
    {"value": "Turquoise", "label": "土耳其蓝色系"},
    {"value": "Mint Green", "label": "薄荷绿色系"},
    {"value": "Maple Red", "label": "枫叶红色系"},
    {"value": "Pop Art", "label": "波普艺术"},
    {"value": "Mountain Blue", "label": "雪山蓝色系"},
    {"value": "black background centered", "label": "黑色背景居中"},
    {"value": "white and green tones", "label": "白色和绿色调"},
    {"value": "red and black tones", "label": "红色和黑色调"},
    {"value": "yellow and black tones", "label": "黄色和黑色调"},
    {"value": "Gold and silver tones", "label": "金色和银色调"},
    {"value": "neon shades", "label": "霓虹色调"},
    {"value": "laser candy paper color", "label": "镭射糖果纸色"},
    {"value": "Macarons", "label": "马卡龙色"},
    {"value": "Muted Tones", "label": "莫兰迪色系"},
    {"value": "Titanium", "label": "钛金属色系"},
    {"value": "Fresh Fruits", "label": "鲜果色系"},
    {"value": "Black and White", "label": "黑白灰色系"},
    {"value": "Minimalist Black and White", "label": "极简黑白色系"},
    {"value": "Warm Brown", "label": "温暖棕色系"},
    {"value": "Soft Pink", "label": "柔和粉色系"},
    {"value": "Fashionable Gray", "label": "时尚灰色系"},
    {"value": "Bright Orange", "label": "亮丽橙色系"},
    {"value": "lvory White", "label": "象牙白色系"},
    {"value": "Natural Green", "label": "自然绿色系"},
    {"value": "Luxurious Gold", "label": "奢华金色系"},
    {"value": "Steady Blue", "label": "稳重蓝色系"},
    {"value": "Classic Red Black and White", "label": "经典红黑白色系"},
    {"value": "Coral Orange", "label": "珊瑚橙色系"},
    {"value": "Whopper", "label": "巨无霸色系"},
    {"value": "Autumn Brown", "label": "秋日棕色系"},
    {"value": "Denim Blue", "label": "丹宁蓝色系"},
    {"value": "Violet Purple", "label": "紫罗兰紫色系"},
    {"value": "Lemon Yellow", "label": "柠檬黄色系"},
    {"value": "Sunset Gradient", "label": "日暮色系"},
    {"value": "Volumetric lighting", "label": "体积光"},
    {"value": "Cold light", "label": "冷色光"},
    {"value": "Mood lighting", "label": "情境灯光"},
    {"value": "Bright", "label": "明亮"},
    {"value": "Soft illumination/ soft lights", "label": "柔和光"},
    {"value": "Fluorescent lighting", "label": "荧光灯"},
    {"value": "Rays of shimmering light/", "label": "耀眼的光线"},
    {"value": "Crepuscular ray", "label": "暮光之光"},
    {"value": "Outer space view", "label": "外太空视角"},
    {"value": "Cinematic lighting/ Dramatic lighting", "label": "电影灯光"},
    {"value": "Bisexual lighting", "label": "双面性灯光"},
    {"value": "Rembrandt lighting", "label": "雷姆布兰特灯光"},
    {"value": "Split lighting", "label": "分光灯光"},
    {"value": "Front lighting", "label": "正面照明"},
    {"value": "Back lighting", "label": "背景照明"},
    {"value": "clean background trending", "label": "千净的背景"},
    {"value": "Rim lighting", "label": "边缘照明"},
    {"value": "Globalilluminations", "label": "全局照明"},
    {"value": "Neon cold lighting", "label": "冷光霓虹灯"},
    {"value": "Hard lighting", "label": "强烈光线"},
    {"value": "Studio lighting", "label": "工作室灯光"},
    {"value": "Natural light", "label": "自然光"},
    {"value": "Indoor lighting", "label": "室内照明"},
    {"value": "Outdoor lighting", "label": "室外照明"},
    {"value": "HDR lighting", "label": "高动态范围照明"},
    {"value": "Real-time lighting", "label": "实时照明"},
    {"value": "Dramatic lighting", "label": "戏剧性灯光"},
    {"value": "Directional light", "label": "定向光"},
    {"value": "Point light", "label": "点光源"},
    {"value": "Spot light", "label": "聚光灯"},
    {"value": "Area light", "label": "区域灯光"},
    {"value": "Ambient light", "label": "环境光"},
    {"value": "Shadow light", "label": "阴影光"},
    {"value": "Sun light", "label": "太阳光"},
    {"value": "Ring light", "label": "环形灯"},
    {"value": "Texture light", "label": "纹理灯"},
    {"value": "Emissive material", "label": "自发光材质"},
    {"value": "Hemisphere light", "label": "半球灯光"},
    {"value": "Panel light", "label": "面板灯"},
    {"value": "Strobe light", "label": "频闪灯"},
    {"value": "morning light", "label": "晨光"}
  ];  


  export const environmentOptions=[
    {"value": "dystopia", "label": "反乌托邦"},
    {"value": "fantasy", "label": "幻想"},
    {"value": "classroom", "label": "教室"},
    {"value": "whimsically", "label": "异想天开"},
    {"value": "bedroom", "label": "卧室"},
    {"value": "ruins", "label": "废墟"},
    {"value": "city", "label": "城市"},
    {"value": "deserted city buildings", "label": "废弃城市建筑群"},
    {"value": "near future city", "label": "近末来都市"},
    {"value": "street scenery", "label": "街景"},
    {"value": "Alchemy Laboratory", "label": "炼金室"},
    {"value": "universe l cosmos", "label": "宇宙"},
    {"value": "rain", "label": "雨天"},
    {"value": "In the morning mist", "label": "在晨雾中"},
    {"value": "full of sunlight", "label": "充满阳光"},
    {"value": "galaxy", "label": "银河"},
    {"value": "dungeon", "label": "暗黑地牢"},
    {"value": "nebula", "label": "星云"},
    {"value": "mad max", "label": "疯狂麦斯沙地风格"},
    {"value": "Hanging Gardens of Babylon", "label": "巴比伦空中花园"},
    {"value": "Underwater world", "label": "水下世界"},
    {"value": "Futuristic metropolis", "label": "未来都市"},
    {"value": "Enchanted garden", "label": "魔法花园"},
    {"value": "Magical castle", "label": "魔法城堡"},
    {"value": "Dreamy clouds", "label": "梦幻云彩"},
    {"value": "Industrial citvscape", "label": "工业城市"},
    {"value": "Cyberpunk city", "label": "赛博朋克城市"},
    {"value": "Dystopian future", "label": "反乌托邦未来"},
    {"value": "Haunted forest", "label": "鬼屋森林"},
    {"value": "Extraterrestrial landscape", "label": "外星地貌"},
    {"value": "Surreal landscape", "label": "超现实主义风景"},
    {"value": "Medieval castle", "label": "中世纪城堡"},
    {"value": "Lunar landscape", "label": "月球地貌"},
    {"value": "Crystal cave", "label": "水晶洞穴"},
    {"value": "Starry night sky", "label": "星空夜景"},
    {"value": "Apocalyptic city", "label": "世界未日城市"},
    {"value": "Lost ruins", "label": "迷失废墟"},
    {"value": "Ice kingdom", "label": "冰雪王国"},
    {"value": "Tropical paradise", "label": "热带天堂"},
    {"value": "Post-apocalyptic wasteland", "label": "后启示录荒野"},
    {"value": "Farmland", "label": "农田"},
    {"value": "Marshland", "label": "沼泽地"},
    {"value": "Canyon", "label": "峡谷"},
    {"value": "seabed", "label": "海底"},
    {"value": "Estuary", "label": "河口"},
    {"value": "Iceberg", "label": "冰山"},
    {"value": "Cloud forest", "label": "两水林"},
    {"value": "Underwater cave", "label": "水下洞穴"},
    {"value": "Steppe", "label": "草原"},
    {"value": "Orchard", "label": "果园"},
    {"value": "Mount Everest", "label": "珠穆朗玛峰"},
    {"value": "wormhole", "label": "时空隧道"},
    {"value": "Ghost town", "label": "幽灵镇"},
    {"value": "Virtual reality", "label": "虚拟现实"},
    {"value": "Alien planet", "label": "外星球"},
    {"value": "Cyberspace", "label": "赛博空问"},
    {"value": "Rift", "label": "时空裂缝"},
    {"value": "Dreamland", "label": "梦境"},
    {"value": "Black hole", "label": "黑洞"},
    {"value": "Otherworld", "label": "灵异空间"},
    {"value": "Enchanted forest", "label": "奇幻森林"},
    {"value": "overgrown nature", "label": "杂草丛生"},
    {"value": "Beach", "label": "海滩"},
    {"value": "Desert", "label": "沙漠"},
    {"value": "Sky garden", "label": "空中花园"},
    {"value": "City park", "label": "城市公园"},
    {"value": "Forest", "label": "森林"},
    {"value": "Mountain", "label": "山脉"},
    {"value": "River", "label": "河流"},
    {"value": "Lake", "label": "湖泊"},
    {"value": "Waterfall", "label": "瀑布"},
    {"value": "Coral reef", "label": "珊瑚礁"},
    {"value": "Glacier", "label": "冰川"},
    {"value": "Snowy mountain", "label": "雪山"},
    {"value": "Cave", "label": "洞穴"},
    {"value": "Grassland", "label": "大草原"},
    {"value": "Dune", "label": "沙滩"},
    {"value": "Lava cave", "label": "熔岩洞穴"},
    {"value": "Wilderness", "label": "荒漠"},
    {"value": "Rainforest", "label": "热带林"},
    {"value": "Sunrise and sunset", "label": "日出和日落"},
    {"value": "Thunderstorm", "label": "雷暴"},
    {"value": "Turbulence", "label": "湍流"},
    {"value": "Fountain", "label": "喷泉"},
    {"value": "Waterfall", "label": "瀑布"},
    {"value": "Ocean waves", "label": "海浪"},
    {"value": "Lightning", "label": "雷电"},
    {"value": "Volcanic eruption", "label": "火山喷发"},
    {"value": "Hurricane", "label": "飓风"},
    {"value": "typhoon", "label": "台风"},
    {"value": "tornado", "label": "龙卷风"},
    {"value": "Mirage", "label": "海市蜃楼"},
    {"value": "volcano", "label": "火山"},
    {"value": "Earthquake", "label": "地震"},
    {"value": "Lunar eclipse", "label": "月食"},
    {"value": "Solar eclipse", "label": "日食"},
    {"value": "Rainbow", "label": "彩虹"},
    {"value": "Tides", "label": "潮汐"},
    {"value": "Gale", "label": "狂风"},
    {"value": "Frost", "label": "霜冻"},
    {"value": "Heavy rain", "label": "暴雨"},
    {"value": "neon lights", "label": "霓虹灯"},
    {"value": "skyscrapers", "label": "摩天大楼"},
    {"value": "onsen", "label": "温泉"},
    {"value": "pool", "label": "水池"},
    {"value": "ruins", "label": "废墟"},
    {"value": "castle", "label": "城堡"},
    {"value": "shrine", "label": "神社"},
    {"value": "hangar", "label": "机库"},
    {"value": "temple", "label": "寺庙"},
    {"value": "windmill", "label": "风车"},
    {"value": "industrial", "label": "重工业"},
    {"value": "floating castle", "label": "浮动城堡"},
    {"value": "poolside", "label": "泳池边"},
    {"value": "alley", "label": "胡同/小巷"},
    {"value": "railroad tracks", "label": "铁轨"},
    {"value": "roller coaster", "label": "过山车"},
    {"value": "trench", "label": "战壕"},
    {"value": "fitting room", "label": "试衣间"},
    {"value": "bathtub", "label": "浴缸"},
    {"value": "bathroom", "label": "浴室场景"},
    {"value": "prison cell", "label": "牢房"},
    {"value": "otaku room", "label": "御宅房"},
    {"value": "courtroom", "label": "法庭"}
  ];  