import i18next from "i18next"

const {t} =i18next;
export const compositionOptions=[
    {"value": "Symmetrical face", "label": "对称面孔"},
    {"value": "volumetric light/Volume Method", "label": "体积光"},
    {"value": "Symmetrical composition", "label": "对称构图"},
    {"value": "Asymmetrical composition", "label": "非对称构图"},
    {"value": "Rule of Thirds composition", "label": "三分法构图"},
    {"value": "Golden Ratio composition", "label": "黄金分割构图"},
    {"value": "Diagonal composition", "label": "对角线构图"},
    {"value": "Dynamic symmetry composition", "label": "动态对称构图"},
    {"value": "Juxtaposition composition", "label": "并列构图"},
    {"value": "Converging lines composition", "label": "汇聚线条构图"},
    {"value": "Vanishing point composition", "label": "消失点构图"},
    {"value": "Framing composition", "label": "画框构图"},
    {"value": "Nonlinear composition", "label": "非线性构图"},
    {"value": "Saturated composition", "label": "饱和构图"},
    {"value": "Point of view composition", "label": "视角构图"},
    {"value": "Cut out composition", "label": "剪影构图"},
    {"value": "Repetition composition", "label": "重复构图"},
    {"value": "Focal point composition", "label": "焦点构图"},
    {"value": "Contrast composition", "label": "对比构图"},
    {"value": "Overlapping composition", "label": "重叠构图"},
    {"value": "Center the composition", "label": "中心构图"},
    {"value": "S-shaped composition", "label": "S形构图"},
    {"value": "Horizontal composition", "label": "横向构图"},
    {"value": "Mandelbrot", "label": "曼德博集合"},
    {"value": "Wide view", "label": "宽景"},
    {"value": "Bird view", "label": "鸟瞰"},
    {"value": "Top view", "label": "俯视"},
    {"value": "Up view", "label": "仰视"},
    {"value": "Front view", "label": "正面"},
    {"value": "Headshot", "label": "头部特写"},
    {"value": "Utrawide shot", "label": "超广角"},
    {"value": "Extreme closeup", "label": "极端特写"},
    {"value": "Macro shot", "label": "微距"},
    {"value": "An expansive view of", "label": "景观"},
    {"value": "Portrait", "label": "肖像"},
    {"value": "Fullbody", "label": "全身"},
    {"value": "Busts", "label": "半身像"},
    {"value": "Close up", "label": "特写"},
    {"value": "Profile", "label": "侧面"},
    {"value": "Symmetrical body", "label": "对称身体"},
    {"value": "Isolation composition", "label": "孤立构图"},
    {"value": "Radial composition", "label": "径向构图"},
    {"value": "split complementary composition", "label": "分割互补构图"},
    {"value": "Mise-en-scene composition", "label": "布景构图"},
    {"value": "Negative space composition", "label": "负空问构图"},
    {"value": "Collage composition", "label": "拼贴构图"},
    {"value": "Rule of Thirds", "label": "三分法"},
    {"value": "Golden Ratio", "label": "黄金分割"},
    {"value": "Symmetry", "label": "对称"},
    {"value": "Asymmetry", "label": "不对称"},
    {"value": "Leading Lines", "label": "引导线"},
    {"value": "Framing", "label": "构框"},
    {"value": "Isolation", "label": "孤立"},
    {"value": "Depth", "label": "深度"},
    {"value": "Contrast", "label": "对比"},
    {"value": "Texture", "label": "纹理"},
    {"value": "Free camera", "label": "自由视角"},
    {"value": "Fixed camera", "label": "固定视角"},
    {"value": "Top-down perspective", "label": "俯视视角"},
    {"value": "Side-scrolling perspective", "label": "侧面视角"},
    {"value": "Close-up view", "label": "短距离视角"},
    {"value": "Long-shot view", "label": "远距离视角"},
    {"value": "Arbitrary view", "label": "随意视角"},
    {"value": "Panoramic view", "label": "全景视角"},
    {"value": "Backlight style", "label": "逆光摄影风格"},
    {"value": "Low Angle Shot", "label": "低角度视角"},
    {"value": "Overhead", "label": "俯拍视角"},
    {"value": "Eye-level", "label": "常规视角"},
    {"value": "Bird's-eye", "label": "鸟瞰视角"},
    {"value": "Dutch", "label": "交错视角"},
    {"value": "Dynamic", "label": "运动视角"},
    {"value": "Extreme Close-up", "label": "极限特写"},
    {"value": "Perspective", "label": "透视视角"},
    {"value": "Detroit: Become Human camera angle", "label": "底特律视角"},
    {"value": "Simulated camera", "label": "模拟摄影机"},
    {"value": "Follow camera", "label": "跟随视角"},
    {"value": "Endoscopic view", "label": "内视镜视角"},
    {"value": "Over the shoulder", "label": "肩膀视角"},
    {"value": "Fisheye lens", "label": "鱼眼视角"},
    {"value": "Macro lens", "label": "微距视角"},
    {"value": "Reverse angle", "label": "反转视角"},
    {"value": "Close-Up(CU)", "label": "特写"},
    {"value": "Medium Close-up(MCu)", "label": "中特写"},
    {"value": "Medium Shot(Ms)", "label": "中景"},
    {"value": "Medium Long Shot(MLS)", "label": "中远暴"},
    {"value": "Long Shot(LS)", "label": "远景"},
    {"value": "Over the Shoulder Shot", "label": "过肩景"},
    {"value": "Loose Shot", "label": "松散景"},
    {"value": "Tight Shot", "label": "近距离景"},
    {"value": "Group Shot(GS)", "label": "群景"},
    {"value": "Scenery Shot", "label": "风景照"},
    {"value": "Bokeh", "label": "背景虚化"},
    {"value": "Foreground", "label": "前景"},
    {"value": "Background", "label": "背景"},
    {"value": "Detail Shot(ECU)", "label": "大特写"},
    {"value": "Chest shot(MCU)", "label": "胸部以上"},
    {"value": "Waist Shot(ws)", "label": "腰部以上"},
    {"value": "Knee Shot(Ks)", "label": "膝盖以上"},
    {"value": "Extra Long Shot(ELS)", "label": "人在远方"},
    {"value": "Big Close-Up(BCu)", "label": "头部以上"},
    {"value": "Face Shot (vCu)", "label": "脸部特写"},
    {"value": "A Bird's-Eye View, Aerial View", "label": "鸟瞰图"},
    {"value": "Top View", "label": "顶视園"},
    {"value": "Tilt-Shift", "label": "倾斜移位"},
    {"value": "Satelite View", "label": "卫星视图"},
    {"value": "Bottom View", "label": "底视图"},
    {"value": "Front, side, Rear view", "label": "前视、侧视、后视图"},
    {"value": "Product View", "label": "产品视图"},
    {"value": "Extreme Closeup View", "label": "极端特写视图"},
    {"value": "Look Up", "label": "仰视"},
    {"value": "First-Person View", "label": "第一人称视角"},
    {"value": "Isometric View", "label": "等距视图"},
    {"value": "Closeup View", "label": "特写视图"},
    {"value": "High Angle View", "label": "高角度视图"}
  ]
  

  export const qualityOptions = [{
    value: ".25",
    label: "普通"
  }, {
    value: ".5",
    label: "一般"
  }, {
    value: "1",
    label: "高清"
  }, {
    value: "2",
    label: "超高清"
  }]



  export const styleOptions = [{
    value: "",
    label: i18next.t("default")
  }, {
    value: "expressive",
    label: t("expressive")
  }, {
    value: "cute",
    label: t("cute")
  }, {
    value: "scenic",
    label: t("scenic")
  }]


  export const style2Options = [
        {"value": "Tradition Chinese Ink Painting", "label": "东方山水画"},
        {"value": "Chinese-style", "label": "中式风格"},
        {"value": "ink illustration", "label": "水墨插图"},
        {"value": "New Chinese Style", "label": "新中式风格"},
        {"value": "Ink Wash Painting Style", "label": "水墨风格"},
        {"value": "color ink on paper", "label": "纸本彩色墨水"},
        {"value": "Traditional culture", "label": "传统文化"},
        {"value": "Japanese Ukiyo-e", "label": "浮世绘"},
        {"value": "Japanese comics/manga", "label": "日本漫画风格"},
        {"value": "poster of japanese graphic design", "label": "日本海报风格"},
        {"value": "Anime", "label": "日本动画片"},
        {"value": "Miyazaki Hayao style", "label": "宫崎骏风格"},
        {"value": "Soejima Shigenori", "label": "副岛成记"},
        {"value": "Yamada Akihiro", "label": "山田章博"},
        {"value": "Ghibli Studio", "label": "吉卜力风格"},
        {"value": "joio's bizarre adventure", "label": "Jolo的奇妙冒险"},
        {"value": "manga", "label": "漫画"},
        {"value": "Japanese-style", "label": "日本风格"},
        {"value": "Magic realism", "label": "魔幻现实"},
        {"value": "Disney-style", "label": "迪士尼风"},
        {"value": "ACGN", "label": "二次元"},
        {"value": "Makoto Shinkai", "label": "新海诚"},
        {"value": "Lolita", "label": "洛丽塔风格"},
        {"value": "stock illustration style", "label": "童话故事书插图风格"},
        {"value": "Watercolor children's illustration", "label": "水彩儿童插画"},
        {"value": "Munashichi", "label": "六七质"},
        {"value": "Hand-drawn style", "label": "手绘风格"},
        {"value": "Cartoon", "label": "卡通"},
        {"value": "Pixel art", "label": "像素风"},
        {"value": "Fairy tale style", "label": "童话风格"},
        {"value": "doodle", "label": "涂鸦"},
        {"value": "Voynich manuscript", "label": "伏尼契手稿"},
        {"value": "CGSociety", "label": "梦工厂动西风格"},
        {"value": "Dreamworks Pictures", "label": "梦工厂黜业"},
        {"value": "Pixar", "label": "皮克斯"},
        {"value": "Pulp Noir", "label": "黑白电影时期"},
        {"value": "Hollywood-style", "label": "电影风格"},
        {"value": "Cinematography style", "label": "电影摄影风格"},
        {"value": "Miniature movie style", "label": "微缩模型电影风格"},
        {"value": "film photography", "label": "剪辑"},
        {"value": "montage", "label": "蒙太奇"},
        {"value": "black and white", "label": "黑白"},
        {"value": "Fashion", "label": "时尚"},
        {"value": "Modern-style", "label": "现代风格"},
        {"value": "interior design", "label": "室内设计"},
        {"value": "Eco-friendly-style", "label": "环保清新风格"},
        {"value": "Country style", "label": "乡村风格"},
        {"value": "Minimalism", "label": "极简主义"},
        {"value": "Immersive design", "label": "沉浸式设计"},
        {"value": "Mystic fantasy", "label": "神秘幻想"},
        {"value": "Modern Minimalist", "label": "现代简约风格"},
        {"value": "Prairie", "label": "草原风格"},
        {"value": "Modern Luxury", "label": "现代奢华风格"},
        {"value": "Forest", "label": "森林风格"},
        {"value": "Ocean", "label": "海洋风格"},
        {"value": "Art Deco style", "label": "艺术装饰风格"},
        {"value": "pearl Milk Tea Style", "label": "珍珠奶茶风格"},
        {"value": "pointillism", "label": "点彩派"},
        {"value": "claude Monet", "label": "克劳德莫奈"},
        {"value": "quilted art", "label": "绗缝艺术"},
        {"value": "partial anatomy", "label": "局部解剖戏"},
        {"value": "9os video game", "label": "90年代电视游戏"},
        {"value": "Game-style", "label": "游戏风格"},
        {"value": "botw", "label": "旷野之息"},
        {"value": "Warframe", "label": "星际战甲"},
        {"value": "Pokemon", "label": "宝可梦"},
        {"value": "x英雄 APEX", "label": "ApeThe Elder Scrolls 上古卷轴"},
        {"value": "From Software", "label": "魂系游戏"},
        {"value": "Detroit: Become Human", "label": "底特律：变人"},
        {"value": "AFK Arena", "label": "剑与远征"},
        {"value": "cookierun kingdom and 跑跑姜饼人", "label": "League of legends 英雄联盟"},
        {"value": "weapon design", "label": "武器设计"},
        {"value": "Game scene graph", "label": "游戏场景图"},
        {"value": "character concept art", "label": "角色概念艺术"},
        {"value": "素风 8、16、24bit", "label": "8、16、24像素画"},
        {"value": "painting", "label": "油画"},
        {"value": "Acrylic painting", "label": "丙烯画"},
        {"value": "volumetric lihht", "label": "体积法"},
        {"value": "french art", "label": "法国艺术"},
        {"value": "Bauhaus", "label": "包豪斯"},
        {"value": "Unity Creations", "label": "统一创作"},
        {"value": "Leonardo Da Vinci", "label": "达芬奇"},
        {"value": "Vincent Van Gogh", "label": "梵高"},
        {"value": "Baroque", "label": "巴洛克吋期"},
        {"value": "Impressionism", "label": "印象派"},
        {"value": "Art Nouveau", "label": "新艺术风格"},
        {"value": "ROCoCO", "label": "洛可可"},
        {"value": "Renaissance", "label": "文艺复兴"},
        {"value": "Cubism", "label": "立体派"},
        {"value": "Stained glass window", "label": "彩色玻璃窗"},
        {"value": "Abstract Art", "label": "抽象表现主义"},
        {"value": "Surrealism", "label": "超现实主义"},
        {"value": "OP Art /Optical Art", "label": "欧普艺术/光效应艺术"},
        {"value": "Abstract", "label": "抽象风"},
        {"value": "Gothic gloomy realism", "label": "写实主义"},
        {"value": "Ethnic Art", "label": "民族艺术"},
        {"value": "riso ", "label": "民族艺术"},
        {"value": "gothic-style", "label": "哥特式"},
        {"value": "full details", "label": "哥特式黑暗"},
        {"value": "Fauvism", "label": "野兽派"},
        {"value": "Minimalist", "label": "极简主义"},
        {"value": "brutalist", "label": "粗犷主义"},
        {"value": "Constructivist", "label": "建构主义"},
        {"value": "concept art", "label": "概念艺术"},
        {"value": "American Country", "label": "美式乡村风格"},
        {"value": "Industrial", "label": "工业风格"},
        {"value": "Carving Art", "label": "雕刻艺术风格"},
        {"value": "Ethnic", "label": "民族风格"},
        {"value": "Magic Realism Style", "label": "魔幻现实主义风格"},
        {"value": "book page", "label": "书页"},
        {"value": "realistic", "label": "真实的"},
        {"value": "3D", "label": "3D风"},
        {"value": "sophisticated", "label": "复杂的"},
        {"value": "photoreal", "label": "真实感"},
        {"value": "national geographic", "label": "国家地理"},
        {"value": "hyperrealism", "label": "超写实主义"},
        {"value": "cinematic", "label": "电影般的"},
        {"value": "architectural sketching", "label": "建筑素描"},
        {"value": "Stained glass window", "label": "彩色玻璃窗"},
        {"value": "Abstract Art", "label": "抽象表现主义"},
        {"value": "Acrylic painting", "label": "丙烯画"},
        {"value": "volumetric lihht", "label": "体积法"},
        {"value": "American Country", "label": "美式乡村风格"},
        {"value": "Pulp Noir", "label": "黑白电影时期"},
        {"value": "Hollywood-style", "label": "电影风格"},
        {"value": "Disney-style", "label": "迪士尼风"}      
  ]